/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PreOrderRouteImport } from './routes/pre-order'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoldOutRouteImport } from './routes/sold-out'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as OrderSuccessIdRouteImport } from './routes/order-success.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin/products.index'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin/products.$id'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated/admin/products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PreOrderRoute = PreOrderRouteImport.update({
  id: '/pre-order',
  path: '/pre-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldOutRoute = SoldOutRouteImport.update({
  id: '/sold-out',
  path: '/sold-out',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessIdRoute = OrderSuccessIdRouteImport.update({
  id: '/order-success/$id',
  path: '/order-success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/pre-order': typeof PreOrderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sold-out': typeof SoldOutRoute
  '/store': typeof StoreRoute
  '/track-order': typeof TrackOrderRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/pre-order': typeof PreOrderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sold-out': typeof SoldOutRoute
  '/store': typeof StoreRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/pre-order': typeof PreOrderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sold-out': typeof SoldOutRoute
  '/store': typeof StoreRoute
  '/track-order': typeof TrackOrderRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/pre-order'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/sold-out'
    | '/store'
    | '/track-order'
    | '/admin'
    | '/account'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$slug'
    | '/admin/categories'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/pre-order'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/sold-out'
    | '/store'
    | '/track-order'
    | '/account'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$slug'
    | '/admin/categories'
    | '/admin/import'
    | '/admin/orders'
    | '/admin'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/pre-order'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/sold-out'
    | '/store'
    | '/track-order'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$slug'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/products/new'
    | '/_authenticated/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  PreOrderRoute: typeof PreOrderRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoldOutRoute: typeof SoldOutRoute
  StoreRoute: typeof StoreRoute
  TrackOrderRoute: typeof TrackOrderRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrderSuccessIdRoute: typeof OrderSuccessIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-order': {
      id: '/pre-order'
      path: '/pre-order'
      fullPath: '/pre-order'
      preLoaderRoute: typeof PreOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold-out': {
      id: '/sold-out'
      path: '/sold-out'
      fullPath: '/sold-out'
      preLoaderRoute: typeof SoldOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$id': {
      id: '/order-success/$id'
      path: '/order-success/$id'
      fullPath: '/order-success/$id'
      preLoaderRoute: typeof OrderSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  PreOrderRoute: PreOrderRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoldOutRoute: SoldOutRoute,
  StoreRoute: StoreRoute,
  TrackOrderRoute: TrackOrderRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrderSuccessIdRoute: OrderSuccessIdRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
